---
abstract: 'Useful IRC objects and utilities'
author:
  - 'Jon Portnoy <avenj@cobaltirc.org>'
build_requires:
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: IRC-Toolkit
requires:
  Carp: 0
  Exporter: 0
  Moo: 1
  POE::Filter::IRCv3: 0
  Scalar::Util: 0
  perl: v5.10.1
  strictures: 1
resources:
  repository: git://github.com/avenj/irc-toolkit.git
version: 0.070003
