---
abstract: 'Useful IRC objects and utilities'
author:
  - 'Jon Portnoy <avenj@cobaltirc.org>'
build_requires:
  ExtUtils::MakeMaker: 0
  File::Spec: 0
  Test::Exception: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.029, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: IRC-Toolkit
requires:
  Carp: 0
  Exporter::Tiny: 0
  List::Objects::Types: 1
  List::Objects::WithUtils: 2
  Moo: 1
  MooX::late: 0.014
  POE::Filter::IRCv3: 0.045
  Role::Tiny: 0
  Scalar::Util: 0
  Storable: 0
  Sub::Infix: 0
  Types::Standard: 0
  namespace::clean: 0
  overload: 0
  strictures: 1
resources:
  repository: git://github.com/avenj/irc-toolkit.git
version: 0.089001
