---
abstract: 'Useful IRC objects and utilities'
author:
  - 'Jon Portnoy <avenj@cobaltirc.org>'
build_requires:
  Test::Exception: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300037, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: IRC-Toolkit
requires:
  Carp: 0
  Exporter::Tiny: 0
  List::Objects::Types: 0.002
  List::Objects::WithUtils: 1.009
  Moo: 1
  POE::Filter::IRCv3: 0.045
  Role::Tiny: 0
  Scalar::Util: 0
  Storable: 0
  namespace::clean: 0
  overload: 0
  perl: v5.8.9
  strictures: 1
resources:
  repository: git://github.com/avenj/irc-toolkit.git
version: 0.085000
